name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install twine
        yarn
    - name: Build
      run: yarn build-package
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*
